# Generated by Django 3.2.3 on 2021-05-24 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('companyid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'company',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Employes',
            fields=[
                ('employeid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('estatus', models.BooleanField()),
                ('companyid', models.ForeignKey(db_column='companyid', on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.company')),
            ],
            options={
                'db_table': 'employes',
                'managed': True,
            },
        ),
    ]
